export const NOTEBOOK_CREATED = 'NOTEBOOK_CREATED';
export const NOTEBOOK_DESTROYED = 'NOTEBOOK_DESTROYED';
export const NOTEBOOK_CELLS_REPLACED = 'NOTEBOOK_CELLS_REPLACED';
export const SETTINGS_CHANGED = 'SETTINGS_CHANGED';
export const INSERT_CELL = 'INSERT_CELL';
export const UPDATE_CELL = 'UPDATE_CELL';
export const REMOVE_CELL_AT_INDEX = 'REMOVE_CELL_AT_INDEX';
